services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: realty-nginx-prod
    ports:
      - "80:80"
    depends_on:
      - frontend-prod
    networks:
      - app-network

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realty-catalog-website-prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge