services:
 nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx

 frontend-prod:
  build:
    context: .
    dockerfile: Dockerfile
  container-name: realty-catalog-website-prod
  networks:
      app-network
      
networks:
  app-network:
    driver: bridge