server {
    listen 80;
    server_name app.reatly-catalog.local;

    location / {
        proxy_pass http://frontend-prod:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}