import type { Property } from "./propiedades.interface";

export const properties: Property[] = [
  {
    id: 1,
    slug: "casa-polanco-herradura",
    title: "Casa Residencial en Polanco",
    type: "casa",
    status: "venta",
    price: 18500000,
    currency: "MXN",
    location: {
      colony: "Polanco V Sección",
      borough: "Miguel Hidalgo",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4328, lng: -99.1944 },
    },
    specs: {
      bedrooms: 4,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 420,
      squareMetersLand: 380,
      floors: 3,
      age: 5,
    },
    amenities: [
      "jardín privado",
      "roof garden",
      "cuarto de servicio",
      "cisterna",
      "alarma",
      "cocina integral",
      "estudio",
    ],
    image: "/images/propiedades/property-1.jpg",
    description:
      "Residencia de lujo en una de las zonas más exclusivas de la ciudad. Acabados de primera, amplios espacios y excelente iluminación natural. A pasos de restaurantes, galerías y centros comerciales de alto nivel.",
    featured: true,
    available: true,
    listedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: 2,
    slug: "penthouse-santa-fe-altitude",
    title: "Penthouse en Santa Fe",
    type: "penthouse",
    status: "venta",
    price: 24900000,
    currency: "MXN",
    location: {
      colony: "Santa Fe",
      borough: "Cuajimalpa",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3607, lng: -99.2617 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 3,
      squareMetersBuilt: 310,
      squareMetersLand: null,
      floors: 1,
      age: 2,
    },
    amenities: [
      "terraza privada",
      "jacuzzi exterior",
      "vista panorámica",
      "gimnasio en edificio",
      "concierge 24h",
      "lobby ejecutivo",
      "bodegas",
    ],
    image: "/images/propiedades/property-2.jpg",
    description:
      "Penthouse con vista de 360° al skyline de Santa Fe. Torre de lujo con amenidades de clase mundial, seguridad perimetral y acabados europeos.",
    featured: true,
    available: true,
    listedAt: "2025-02-03T09:00:00Z",
  },
  {
    id: 3,
    slug: "departamento-condesa-parque",
    title: "Departamento Frente al Parque en Condesa",
    type: "departamento",
    status: "renta",
    price: 28000,
    currency: "MXN",
    location: {
      colony: "Hipódromo Condesa",
      borough: "Cuauhtémoc",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4117, lng: -99.1745 },
    },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      halfBathrooms: 0,
      parkingSpots: 1,
      squareMetersBuilt: 110,
      squareMetersLand: null,
      floors: 1,
      age: 15,
    },
    amenities: [
      "balcón",
      "pet friendly",
      "roof garden compartido",
      "bicicleta incluida",
      "cuarto de lavado",
      "intercomunicador",
    ],
    image: "/images/propiedades/property-3.jpg",
    description:
      "Luminoso departamento con vista directa al Parque México. Edificio art déco remodelado, zona caminable con los mejores cafés y restaurantes de la colonia.",
    featured: false,
    available: true,
    listedAt: "2025-03-15T10:00:00Z",
  },
  {
    id: 4,
    slug: "casa-coyoacan-colonial",
    title: "Casa Moderna en Coyoacán",
    type: "casa",
    status: "venta",
    price: 9800000,
    currency: "MXN",
    location: {
      colony: "Del Carmen",
      borough: "Coyoacán",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3467, lng: -99.1617 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 280,
      squareMetersLand: 320,
      floors: 2,
      age: 40,
    },
    amenities: [
      "patio interior",
      "estudio",
      "chimenea",
      "vigas de madera",
      "cocina remodelada",
      "cisterna",
      "cuarto de servicio",
    ],
    image: "/images/propiedades/property-4.jpg",
    description:
      "Casona colonial restaurada con todo el encanto del Coyoacán histórico. Techos altos, cantera rosa y patio interior con fuente. A dos cuadras del Jardín Centenario.",
    featured: true,
    available: true,
    listedAt: "2025-01-28T11:00:00Z",
  },
  {
    id: 5,
    slug: "departamento-roma-norte-moderno",
    title: "Departamento Moderno en Roma Norte",
    type: "departamento",
    status: "renta",
    price: 22000,
    currency: "MXN",
    location: {
      colony: "Roma Norte",
      borough: "Cuauhtémoc",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4189, lng: -99.1601 },
    },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      halfBathrooms: 0,
      parkingSpots: 1,
      squareMetersBuilt: 75,
      squareMetersLand: null,
      floors: 1,
      age: 3,
    },
    amenities: [
      "terraza privada",
      "cocina abierta",
      "doble altura",
      "smart home",
      "bike parking",
      "seguridad 24h",
    ],
    image: "/images/propiedades/property-5.jpg",
    description:
      "Departamento de diseño en edificio boutique de Roma Norte. Acabados minimalistas, ventanales de piso a techo y ubicación privilegiada a pasos del metro Insurgentes.",
    featured: false,
    available: true,
    listedAt: "2025-04-01T09:30:00Z",
  },
  {
    id: 6,
    slug: "casa-pedregal-jardines",
    title: "Residencia en Jardines del Pedregal",
    type: "casa",
    status: "venta",
    price: 32000000,
    currency: "MXN",
    location: {
      colony: "Jardines del Pedregal",
      borough: "Álvaro Obregón",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3231, lng: -99.1972 },
    },
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBathrooms: 2,
      parkingSpots: 4,
      squareMetersBuilt: 780,
      squareMetersLand: 900,
      floors: 3,
      age: 8,
    },
    amenities: [
      "alberca climatizada",
      "cine privado",
      "cancha de pádel",
      "gimnasio privado",
      "jardín con riego automático",
      "cuartos de servicio",
      "generador de emergencia",
      "cava de vinos",
    ],
    image: "/images/propiedades/property-6.jpg",
    description:
      "Residencia ultra-premium en la zona más exclusiva del sur de la ciudad. Arquitectura contemporánea con materiales importados, domótica integrada y seguridad privada las 24 horas.",
    featured: true,
    available: true,
    listedAt: "2024-12-05T08:00:00Z",
  },
  {
    id: 7,
    slug: "departamento-narvarte-familiar",
    title: "Departamento Familiar en Narvarte",
    type: "departamento",
    status: "venta",
    price: 4200000,
    currency: "MXN",
    location: {
      colony: "Narvarte Poniente",
      borough: "Benito Juárez",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3978, lng: -99.1583 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 145,
      squareMetersLand: null,
      floors: 1,
      age: 10,
    },
    amenities: [
      "salón de usos múltiples",
      "roof garden compartido",
      "cuarto de lavado",
      "bodegas",
      "intercomunicador",
      "vigilancia",
    ],
    image: "/images/propiedades/property-7.jpg",
    description:
      "Amplio departamento ideal para familias en la tranquila Narvarte. Excelente conectividad con Metrobús y Línea 3 del Metro. Zona segura con comercio local a pie de calle.",
    featured: false,
    available: true,
    listedAt: "2025-02-20T10:00:00Z",
  },
  {
    id: 8,
    slug: "penthouse-lomas-chapultepec",
    title: "Penthouse en Lomas de Chapultepec",
    type: "penthouse",
    status: "renta",
    price: 85000,
    currency: "MXN",
    location: {
      colony: "Lomas de Chapultepec IV Sección",
      borough: "Miguel Hidalgo",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4267, lng: -99.2089 },
    },
    specs: {
      bedrooms: 4,
      bathrooms: 4,
      halfBathrooms: 1,
      parkingSpots: 3,
      squareMetersBuilt: 380,
      squareMetersLand: null,
      floors: 2,
      age: 6,
    },
    amenities: [
      "terraza doble nivel",
      "jacuzzi privado",
      "cocina gourmet",
      "sala de juntas",
      "concierge",
      "valet parking",
      "spa en edificio",
    ],
    image: "/images/propiedades/property-8.jpg",
    description:
      "Penthouse de doble nivel con vista al Bosque de Chapultepec. Torre de acceso controlado con amenidades de hotel cinco estrellas. Ideal para ejecutivos internacionales.",
    featured: true,
    available: true,
    listedAt: "2025-03-01T08:00:00Z",
  },
  {
    id: 9,
    slug: "casa-xochimilco-ecologica",
    title: "Casa Ecológica en Xochimilco",
    type: "casa",
    status: "venta",
    price: 6500000,
    currency: "MXN",
    location: {
      colony: "Barrio San Lucas",
      borough: "Xochimilco",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.2572, lng: -99.1028 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      halfBathrooms: 0,
      parkingSpots: 2,
      squareMetersBuilt: 210,
      squareMetersLand: 450,
      floors: 2,
      age: 1,
    },
    amenities: [
      "paneles solares",
      "captación de agua pluvial",
      "huerto orgánico",
      "composta",
      "calentador solar",
      "jardín nativo",
      "muro verde",
    ],
    image: "/images/propiedades/property-9.jpg",
    description:
      "Casa de construcción sustentable en los límites de la Zona Patrimonio de la Humanidad. Materiales locales, diseño bioclimático y amplio terreno con vista a los canales.",
    featured: false,
    available: true,
    listedAt: "2025-04-10T08:00:00Z",
  },
  {
    id: 10,
    slug: "penthouse-polanco-moderno",
    title: "Penthouse Moderno en Polanco",
    type: "penthouse",
    status: "venta",
    price: 19800000,
    currency: "MXN",
    location: {
      colony: "Polanco II Sección",
      borough: "Miguel Hidalgo",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4312, lng: -99.1978 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 290,
      squareMetersLand: null,
      floors: 1,
      age: 4,
    },
    amenities: [
      "terraza privada",
      "cocina italiana",
      "vestidor",
      "smart home",
      "concierge 24h",
      "alberca en edificio",
    ],
    image: "/images/propiedades/property-10.jpg",
    description:
      "Penthouse de diseño contemporáneo en el corazón de Polanco. Ventanales de piso a techo, acabados de importación y terraza con vista a Av. Presidente Masaryk.",
    featured: true,
    available: true,
    listedAt: "2025-02-14T09:00:00Z",
  },
  {
    id: 11,
    slug: "casa-coyoacan-moderna",
    title: "Casa Colonial en Coyoacán",
    type: "casa",
    status: "renta",
    price: 45000,
    currency: "MXN",
    location: {
      colony: "Jardines del Pedregal de San Ángel",
      borough: "Coyoacán",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3389, lng: -99.1756 },
    },
    specs: {
      bedrooms: 4,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 320,
      squareMetersLand: 280,
      floors: 2,
      age: 7,
    },
    amenities: [
      "jardín privado",
      "alberca",
      "cuarto de servicio",
      "estudio",
      "cocina integral",
      "alarma",
      "cisterna",
    ],
    image: "/images/propiedades/property-11.jpg",
    description:
      "Casa de arquitectura contemporánea en renta en una de las colonias más tranquilas de Coyoacán. Amplios espacios, jardín privado con alberca y acabados de calidad.",
    featured: false,
    available: true,
    listedAt: "2025-03-20T10:00:00Z",
  },
  {
    id: 12,
    slug: "departamento-benito-juarez-ejecutivo",
    title: "Departamento Ejecutivo en Benito Juárez",
    type: "departamento",
    status: "renta",
    price: 18500,
    currency: "MXN",
    location: {
      colony: "Del Valle Norte",
      borough: "Benito Juárez",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3891, lng: -99.1712 },
    },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      halfBathrooms: 0,
      parkingSpots: 1,
      squareMetersBuilt: 68,
      squareMetersLand: null,
      floors: 1,
      age: 5,
    },
    amenities: [
      "gimnasio",
      "roof garden",
      "seguridad 24h",
      "intercomunicador",
      "bike parking",
      "área de coworking",
    ],
    image: "/images/propiedades/property-12.jpg",
    description:
      "Departamento ejecutivo en edificio nuevo con amenidades completas. Ubicación estratégica cerca de World Trade Center y principales vías de acceso.",
    featured: false,
    available: true,
    listedAt: "2025-04-05T08:30:00Z",
  },
  {
    id: 13,
    slug: "casa-alvaro-obregon-residencial",
    title: "Casa Residencial en Álvaro Obregón",
    type: "casa",
    status: "renta",
    price: 38000,
    currency: "MXN",
    location: {
      colony: "Tizapán San Ángel",
      borough: "Álvaro Obregón",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3456, lng: -99.2034 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 260,
      squareMetersLand: 300,
      floors: 2,
      age: 12,
    },
    amenities: [
      "jardín",
      "estudio",
      "chimenea",
      "cocina equipada",
      "cuarto de servicio",
      "cisterna",
      "alarma",
    ],
    image: "/images/propiedades/property-13.jpg",
    description:
      "Hermosa casa en renta en la tranquila colonia Tizapán San Ángel. Rodeada de áreas verdes, cerca de universidades y centros culturales del sur de la ciudad.",
    featured: false,
    available: true,
    listedAt: "2025-03-08T09:00:00Z",
  },
  {
    id: 14,
    slug: "penthouse-cuajimalpa-bosques",
    title: "Penthouse en Bosques de las Lomas",
    type: "penthouse",
    status: "renta",
    price: 72000,
    currency: "MXN",
    location: {
      colony: "Bosques de las Lomas",
      borough: "Cuajimalpa",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3712, lng: -99.2534 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 3,
      squareMetersBuilt: 340,
      squareMetersLand: null,
      floors: 2,
      age: 9,
    },
    amenities: [
      "terraza panorámica",
      "jacuzzi",
      "cocina gourmet",
      "vestidor",
      "concierge",
      "valet parking",
      "spa",
    ],
    image: "/images/propiedades/property-14.jpg",
    description:
      "Exclusivo penthouse en Bosques de las Lomas con vista privilegiada al bosque. Amenidades de primer nivel y acceso a los mejores restaurantes y centros comerciales de Santa Fe.",
    featured: true,
    available: true,
    listedAt: "2025-02-25T10:00:00Z",
  },
  {
    id: 15,
    slug: "departamento-xochimilco-nuevo",
    title: "Departamento Nuevo en Xochimilco",
    type: "departamento",
    status: "venta",
    price: 2800000,
    currency: "MXN",
    location: {
      colony: "San Juan Tepepan",
      borough: "Xochimilco",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.2634, lng: -99.0945 },
    },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      halfBathrooms: 0,
      parkingSpots: 1,
      squareMetersBuilt: 92,
      squareMetersLand: null,
      floors: 1,
      age: 1,
    },
    amenities: [
      "roof garden",
      "área de asadores",
      "seguridad",
      "intercomunicador",
      "cuarto de lavado",
      "cisterna",
    ],
    image: "/images/propiedades/property-15.jpg",
    description:
      "Departamento nuevo en desarrollo habitacional en Xochimilco. Excelente opción de inversión en una zona con gran plusvalía y a minutos de los canales patrimonio de la humanidad.",
    featured: false,
    available: true,
    listedAt: "2025-04-12T08:00:00Z",
  },
  {
    id: 16,
    slug: "casa-miguel-hidalgo-lomas",
    title: "Casa en Lomas de Chapultepec",
    type: "casa",
    status: "venta",
    price: 22500000,
    currency: "MXN",
    location: {
      colony: "Lomas de Chapultepec II Sección",
      borough: "Miguel Hidalgo",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4289, lng: -99.2112 },
    },
    specs: {
      bedrooms: 5,
      bathrooms: 4,
      halfBathrooms: 2,
      parkingSpots: 4,
      squareMetersBuilt: 620,
      squareMetersLand: 700,
      floors: 3,
      age: 15,
    },
    amenities: [
      "alberca",
      "jardín amplio",
      "cuartos de servicio",
      "cava",
      "estudio",
      "sala de cine",
      "gimnasio privado",
      "generador",
    ],
    image: "/images/propiedades/property-16.jpg",
    description:
      "Majestuosa residencia en Lomas de Chapultepec con todas las comodidades. Amplios jardines, alberca y acabados de lujo en una de las zonas más prestigiosas de la ciudad.",
    featured: true,
    available: true,
    listedAt: "2025-01-15T08:00:00Z",
  },
  {
    id: 17,
    slug: "departamento-cuauhtemoc-reforma",
    title: "Departamento en Paseo de la Reforma",
    type: "departamento",
    status: "venta",
    price: 7600000,
    currency: "MXN",
    location: {
      colony: "Cuauhtémoc",
      borough: "Cuauhtémoc",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.4278, lng: -99.1623 },
    },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      halfBathrooms: 1,
      parkingSpots: 1,
      squareMetersBuilt: 128,
      squareMetersLand: null,
      floors: 1,
      age: 6,
    },
    amenities: [
      "vista a Reforma",
      "balcón",
      "gimnasio",
      "alberca",
      "concierge",
      "seguridad 24h",
      "bodegas",
    ],
    image: "/images/propiedades/property-17.jpg",
    description:
      "Departamento con vista privilegiada al Paseo de la Reforma y al Ángel de la Independencia. Torre icónica con amenidades de lujo en el corredor financiero más importante del país.",
    featured: true,
    available: true,
    listedAt: "2025-02-08T09:00:00Z",
  },
  {
    id: 18,
    slug: "penthouse-benito-juarez-del-valle",
    title: "Penthouse en Del Valle",
    type: "penthouse",
    status: "venta",
    price: 12400000,
    currency: "MXN",
    location: {
      colony: "Del Valle Centro",
      borough: "Benito Juárez",
      city: "Ciudad de México",
      state: "CDMX",
      coordinates: { lat: 19.3834, lng: -99.1689 },
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      halfBathrooms: 1,
      parkingSpots: 2,
      squareMetersBuilt: 265,
      squareMetersLand: null,
      floors: 2,
      age: 3,
    },
    amenities: [
      "terraza privada",
      "roof garden exclusivo",
      "cocina integral",
      "vestidor",
      "smart home",
      "gimnasio en edificio",
      "salón de eventos",
    ],
    image: "/images/propiedades/property-18.jpg",
    description:
      "Espectacular penthouse de doble nivel en Del Valle con terraza privada y roof garden exclusivo. Edificio boutique de solo 8 unidades, máxima privacidad y acabados europeos.",
    featured: false,
    available: true,
    listedAt: "2025-03-28T09:00:00Z",
  },
];
